### ISSUE TITLE
How get psnr after reading img by cv2.imread(opencv)

### ISSUE THREAD

**Issue by zhouhang95** [andrewekhalel/sewar#6]
as title

**Comment by zhouhang95** [comment]
In readme, I don't konw the format of img, Numpy or other ? (HxWxC) or (CxHxW)? RGB or BGR? 0-1 or 0-255?

**Comment by andrewekhalel** [comment]
Hello @zhouhang95,
In PSNR is a full reference metrics. Check usage example [here](https://github.com/andrewekhalel/sewar#example-usage) (replace uqi with psnr in your case).

The functions were tested on numpy arrays in (HxWxC) format. I believe the other options should work also. You have to set MAX parameter in order to define the maximum pixel value of your image.
